main: com.scuffpvp.ScuffPVP
name: ScuffPVP
version: '0.1'
api-version: '1.20'
commands:
  class:
    description: Chooses a class for the nearest player
    usage: /class className
    permission: scuffpvp.player
  start:
    description: Starts a game
    usage: /start
    permission: scuffpvp.admin
  vote:
    description: Votes for a map
    usage: /vote map
    permission: scuffpvp.player
  startSelection:
    description: Starts a map vote
    usage: /startSelection
    permission: scuffpvp.admin
permissions:
  scuffpvp.player:
    description: Default player permission
    default: true
  scuffpvp.admin:
    description: Default op permission
    default: op